import os
REPO=os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)),"..","..",".."))
import re, struct
from fractions import Fraction
from decimal import Decimal

def bits(x: float) -> int:
    return struct.unpack('<Q', struct.pack('<d', x))[0]

def expect_round(y_lit: str, n: int) -> str:
    y = float(y_lit)
    neg = (bits(y) >> 63) == 1
    if y == 0.0:
        return f".zero {'true' if neg else 'false'}"
    q = Fraction(Decimal(y_lit)) * 10**n
    assert q.denominator == 1, (y_lit, n)
    q = abs(int(q))
    # sanity: the literal scaled is an integer and float(q/10^n) is the golden
    assert float(Fraction(q, 10**n)) == abs(y)
    return f".val {'true' if neg else 'false'} {q}"

rounds = []   # (bits, n, expected RoundResult, comment)
gold = []  # (bits, n, expected bits)
fmts = []     # (bits, n, expected string, comment)
diverge = []

def handle(line, src):
    line = line.strip()
    if not line or line.startswith('#'):
        return False
    m = re.match(r'Float\.round\(([^,]+),\s*(\d+)\)\s*=\s*(\S+)', line)
    if m:
        x, n, y = m.group(1), int(m.group(2)), m.group(3)
        gold.append((bits(float(x)), n, bits(float(y))))
        if abs(float(x)) > 2**53 / 10**n:
            assert float(y) == float(x)
            rounds.append((bits(float(x)), n, ".keep", f"{src}: {line}"))
        else:
            rounds.append((bits(float(x)), n, expect_round(y, n), f"{src}: {line}"))
        return True
    m = re.match(r'round\(([^)]+)\)\s*=\s*(\S+)', line)
    if m:
        x, y = m.group(1), m.group(2)
        gold.append((bits(float(x)), 0, bits(float(y))))
        rounds.append((bits(float(x)), 0, expect_round(y, 0), f"{src}: {line}"))
        return True
    m = re.match(r'ftb2\(([^)]+)\)\s*=\s*(\S+)', line)
    if m:
        fmts.append((bits(float(m.group(1))), 2, m.group(2), f"{src}: {line}"))
        return True
    m = re.match(r'ftb\(([^)]+)\)\s*=\s*(\S+)', line)
    if m:
        x, s = m.group(1), m.group(2)
        if x == '5.0e-7':
            diverge.append((bits(float(x)), 6, s, "0.0", f"{src}: {line}"))
        else:
            fmts.append((bits(float(x)), 6, s, f"{src}: {line}"))
        return True
    m = re.match(r'float_to_binary\((\S+), (\[:compact, )?decimals: 6\]?\)\s*=\s*(\S+)', line)
    if m:
        diverge.append((bits(float(m.group(1))), 6, m.group(3), "0.0", f"{src}: {line}"))
        return True
    return False

n_fs = 0
for line in open(REPO+'/goldens/float-semantics.txt'):
    if handle(line, 'float-semantics'):
        n_fs += 1
n_pr = 0
sec = None
for line in open(REPO+'/goldens/semantics-probes.txt'):
    if line.startswith('## '):
        sec = line[3:5]
        continue
    if sec in ('E1', 'E3', 'E8') and not line.startswith('  {') and not line.startswith('tempo'):
        if handle(line, f'probes {sec}'):
            n_pr += 1

with open('Table.lean', 'w') as f:
    f.write('-- GENERATED by gen_table.py from goldens/float-semantics.txt and semantics-probes.txt (E1/E3/E8)\n')
    f.write('import Decfmt\nnamespace Decfmt\n\n')
    f.write('/-- (input bits, n, expected value-rounding result) -/\n')
    f.write('def roundTable : List (UInt64 × Nat × RoundResult) := [\n')
    f.write('\n'.join(f'  (0x{b:016X}, {n}, RoundResult{e}){"," if i < len(rounds)-1 else ""}  -- {c}' for i, (b, n, e, c) in enumerate(rounds)))
    f.write('\n]\n\n')
    f.write('/-- (input bits, n, expected formatted string) -/\n')
    f.write('def fmtTable : List (UInt64 × Nat × String) := [\n')
    f.write('\n'.join(f'  (0x{b:016X}, {n}, "{s}"){"," if i < len(fmts)-1 else ""}  -- {c}' for i, (b, n, s, c) in enumerate(fmts)))
    f.write('\n]\n\n')
    f.write('/-- expected-to-diverge formatter lines: (bits, n, oracle string, exact-rule string) -/\n')
    f.write('def divergeTable : List (UInt64 × Nat × String × String) := [\n')
    f.write('\n'.join(f'  (0x{b:016X}, {n}, "{s}", "{t}"){"," if i < len(diverge)-1 else ""}  -- {c}' for i, (b, n, s, t, c) in enumerate(diverge)))
    f.write('\n]\n\n')
    f.write('/-- (input bits, n, f64 bits of the golden literal) for the Float.round / round lines, for the #eval Float check -/\n')
    f.write('def goldenFloatBits : List (UInt64 × Nat × UInt64) := [\n')
    f.write('\n'.join(f'  (0x{b:016X}, {n}, 0x{y:016X}){"," if i < len(gold)-1 else ""}' for i, (b, n, y) in enumerate(gold)))
    f.write('\n]\n\nend Decfmt\n')
print("float-semantics lines in scope:", n_fs, "probe lines in scope:", n_pr)
print("round checks:", len(rounds), "fmt checks:", len(fmts), "diverge:", len(diverge))
# Also: Rust sample inputs list for the scratch program
with open('rs/inputs.txt', 'w') as f:
    seen = set()
    for b, n, e, c in rounds:
        if (b, n) not in seen:
            seen.add((b, n)); f.write(f'{b:016X} {n}\n')
# domain thresholds: spec rational vs Rust float
for n in (0, 2, 3, 6):
    D = 2.0**53 / float(10**n)
    ex = Fraction(2**53, 10**n)
    print(f"n={n}: Rust threshold float {D!r} vs exact {float(ex)!r}; float-exact = {Fraction(D) - ex}")
