-- GENERATED by gen_table.py from goldens/float-semantics.txt and semantics-probes.txt (E1/E3/E8)
import Decfmt
namespace Decfmt

/-- (input bits, n, expected value-rounding result) -/
def roundTable : List (UInt64 × Nat × RoundResult) := [
  (0x3FE0000000000000, 0, RoundResult.val false 1),  -- float-semantics: round(0.5) = 1
  (0x3FF8000000000000, 0, RoundResult.val false 2),  -- float-semantics: round(1.5) = 2
  (0x4004000000000000, 0, RoundResult.val false 3),  -- float-semantics: round(2.5) = 3
  (0xBFE0000000000000, 0, RoundResult.val true 1),  -- float-semantics: round(-0.5) = -1
  (0xBFF8000000000000, 0, RoundResult.val true 2),  -- float-semantics: round(-1.5) = -2
  (0x4060880000000000, 0, RoundResult.val false 132),  -- float-semantics: round(132.25) = 132
  (0x4060900000000000, 0, RoundResult.val false 133),  -- float-semantics: round(132.5) = 133
  (0x3FC0000000000000, 2, RoundResult.val false 13),  -- float-semantics: Float.round(0.125, 2) = 0.13
  (0x3FD8000000000000, 2, RoundResult.val false 38),  -- float-semantics: Float.round(0.375, 2) = 0.38
  (0xBFC0000000000000, 2, RoundResult.val true 13),  -- float-semantics: Float.round(-0.125, 2) = -0.13
  (0x3FB0000000000000, 3, RoundResult.val false 63),  -- float-semantics: Float.round(0.0625, 3) = 0.063
  (0x4004000000000000, 0, RoundResult.val false 3),  -- float-semantics: Float.round(2.5, 0) = 3.0
  (0x3FE0000000000000, 0, RoundResult.val false 1),  -- float-semantics: Float.round(0.5, 0) = 1.0
  (0x3FF8000000000000, 0, RoundResult.val false 2),  -- float-semantics: Float.round(1.5, 0) = 2.0
  (0x4005666666666666, 2, RoundResult.val false 267),  -- float-semantics: Float.round(2.675, 2) = 2.67
  (0x3FD23D70A3D70A3D, 2, RoundResult.val false 28),  -- float-semantics: Float.round(0.285, 2) = 0.28
  (0x3FF0147AE147AE14, 2, RoundResult.val false 100),  -- float-semantics: Float.round(1.005, 2) = 1.0
  (0x3F80000000000000, 6, RoundResult.val false 7813),  -- float-semantics: Float.round(0.0078125, 6) = 0.007813
  (0x3FB2000000000000, 6, RoundResult.val false 70313),  -- float-semantics: Float.round(0.0703125, 6) = 0.070313
  (0xBF80000000000000, 6, RoundResult.val true 7813),  -- float-semantics: Float.round(-0.0078125, 6) = -0.007813
  (0x403B45D1745D1746, 3, RoundResult.val false 27273),  -- float-semantics: Float.round(27.272727272727273, 3) = 27.273
  (0xC03B45D1745D1746, 3, RoundResult.val true 27273),  -- float-semantics: Float.round(-27.272727272727273, 3) = -27.273
  (0x3F9BED61BED61BD8, 3, RoundResult.val false 27),  -- float-semantics: Float.round(0.0272727272727272, 3) = 0.027
  (0x3E7AD7F29ABCAF48, 6, RoundResult.zero false),  -- float-semantics: Float.round(1.0e-7, 6) = 0.0
  (0x3FEFFFFEF39085F5, 6, RoundResult.val false 1000000),  -- float-semantics: Float.round(0.9999995, 6) = 1.0
  (0x4064D55555555556, 3, RoundResult.val false 166667),  -- float-semantics: Float.round(166.66666666666669, 3) = 166.667
  (0x3FE5555555555555, 2, RoundResult.val false 67),  -- float-semantics: Float.round(0.6666666666666666, 2) = 0.67
  (0xBF1A36E2EB1C432D, 3, RoundResult.zero false),  -- probes E1: Float.round(-1.0e-4, 3)  = 0.0   (sign bit 0)
  (0xBE7AD7F29ABCAF48, 6, RoundResult.zero false),  -- probes E1: Float.round(-1.0e-7, 6)  = 0.0   (sign bit 0)
  (0x8000000000000000, 3, RoundResult.zero true),  -- probes E1: Float.round(-0.0, 3)     = -0.0  (sign bit 1)
  (0xBFC0000000000000, 3, RoundResult.val true 125),  -- probes E1: Float.round(-0.125, 3)   = -0.125  (nonzero results keep their sign)
  (0x3EA0C6F7A0B5ED8D, 6, RoundResult.zero false),  -- probes E3: Float.round(5.0e-7, 6)                         = 0.0
  (0x4324438E98E94EA1, 6, RoundResult.keep)  -- probes E8: Float.round(2851889632028496.5, 6) = 2851889632028496.5
]

/-- (input bits, n, expected formatted string) -/
def fmtTable : List (UInt64 × Nat × String) := [
  (0x0000000000000000, 6, "0.0"),  -- float-semantics: ftb(0.0) = 0.0
  (0x8000000000000000, 6, "-0.0"),  -- float-semantics: ftb(-0.0) = -0.0
  (0x3FF0000000000000, 6, "1.0"),  -- float-semantics: ftb(1.0) = 1.0
  (0x3FEE666666666666, 6, "0.95"),  -- float-semantics: ftb(0.95) = 0.95
  (0xBFC3333333333333, 6, "-0.15"),  -- float-semantics: ftb(-0.15) = -0.15
  (0x403B45E353F7CED9, 6, "27.273"),  -- float-semantics: ftb(27.273) = 27.273
  (0x403B45E353F7CEDA, 6, "27.273"),  -- float-semantics: ftb(27.273000000000003) = 27.273
  (0x3F4083DBC23315D7, 6, "0.000504"),  -- float-semantics: ftb(5.04e-4) = 0.000504
  (0x405EDD3C08596AD5, 6, "123.456789"),  -- float-semantics: ftb(123.4567891) = 123.456789
  (0x3E7AD7F29ABCAF48, 6, "0.0"),  -- float-semantics: ftb(1.0e-7) = 0.0
  (0xBE7AD7F29ABCAF48, 6, "-0.0"),  -- float-semantics: ftb(-1.0e-7) = -0.0
  (0x3FEFFFFEF39085F5, 6, "1.0"),  -- float-semantics: ftb(0.9999995) = 1.0
  (0x3FEFFFFEEE32223C, 6, "0.999999"),  -- float-semantics: ftb(0.99999949) = 0.999999
  (0x400528F5C28F5C28, 6, "2.645"),  -- float-semantics: ftb(2.6449999999999996) = 2.645
  (0x40178AC921996A0C, 6, "5.885533"),  -- float-semantics: ftb(5.885532879818594) = 5.885533
  (0x4059000000000000, 6, "100.0"),  -- float-semantics: ftb(100.0) = 100.0
  (0x3FD0000000000000, 6, "0.25"),  -- float-semantics: ftb(0.25) = 0.25
  (0xC010000000000000, 6, "-4.0"),  -- float-semantics: ftb(-4.0) = -4.0
  (0x3EB92A737110E454, 6, "0.000002"),  -- float-semantics: ftb(1.5e-6) = 0.000002
  (0x3EC4F8B588E368F1, 6, "0.000003"),  -- float-semantics: ftb(2.5e-6) = 0.000003
  (0x4005666666666666, 6, "2.675"),  -- float-semantics: ftb(2.675) = 2.675
  (0x3FD23D70A3D70A3D, 6, "0.285"),  -- float-semantics: ftb(0.285) = 0.285
  (0x3F80000000000000, 6, "0.007813"),  -- float-semantics: ftb(0.0078125) = 0.007813
  (0x3FB2000000000000, 6, "0.070313"),  -- float-semantics: ftb(0.0703125) = 0.070313
  (0xBF80000000000000, 6, "-0.007813"),  -- float-semantics: ftb(-0.0078125) = -0.007813
  (0x4005666666666666, 2, "2.67"),  -- float-semantics: ftb2(2.675) = 2.67
  (0x3FD23D70A3D70A3D, 2, "0.28"),  -- float-semantics: ftb2(0.285) = 0.28
  (0x3FF0147AE147AE14, 2, "1.0"),  -- float-semantics: ftb2(1.005) = 1.0
  (0x3FC0000000000000, 2, "0.13")  -- float-semantics: ftb2(0.125) = 0.13
]

/-- expected-to-diverge formatter lines: (bits, n, oracle string, exact-rule string) -/
def divergeTable : List (UInt64 × Nat × String × String) := [
  (0x3EA0C6F7A0B5ED8D, 6, "0.000001", "0.0"),  -- float-semantics: ftb(5.0e-7) = 0.000001
  (0x3EA0C6F7A0B5ED8D, 6, "0.000001", "0.0"),  -- probes E3: float_to_binary(5.0e-7, decimals: 6)           = 0.000001
  (0x3EA0C6F7A0B5ED8D, 6, "0.000001", "0.0")  -- probes E3: float_to_binary(5.0e-7, [:compact, decimals: 6]) = 0.000001
]

/-- (input bits, n, f64 bits of the golden literal) for the Float.round / round lines, for the #eval Float check -/
def goldenFloatBits : List (UInt64 × Nat × UInt64) := [
  (0x3FE0000000000000, 0, 0x3FF0000000000000),
  (0x3FF8000000000000, 0, 0x4000000000000000),
  (0x4004000000000000, 0, 0x4008000000000000),
  (0xBFE0000000000000, 0, 0xBFF0000000000000),
  (0xBFF8000000000000, 0, 0xC000000000000000),
  (0x4060880000000000, 0, 0x4060800000000000),
  (0x4060900000000000, 0, 0x4060A00000000000),
  (0x3FC0000000000000, 2, 0x3FC0A3D70A3D70A4),
  (0x3FD8000000000000, 2, 0x3FD851EB851EB852),
  (0xBFC0000000000000, 2, 0xBFC0A3D70A3D70A4),
  (0x3FB0000000000000, 3, 0x3FB020C49BA5E354),
  (0x4004000000000000, 0, 0x4008000000000000),
  (0x3FE0000000000000, 0, 0x3FF0000000000000),
  (0x3FF8000000000000, 0, 0x4000000000000000),
  (0x4005666666666666, 2, 0x40055C28F5C28F5C),
  (0x3FD23D70A3D70A3D, 2, 0x3FD1EB851EB851EC),
  (0x3FF0147AE147AE14, 2, 0x3FF0000000000000),
  (0x3F80000000000000, 6, 0x3F8000431BDE82D8),
  (0x3FB2000000000000, 6, 0x3FB20008637BD05B),
  (0xBF80000000000000, 6, 0xBF8000431BDE82D8),
  (0x403B45D1745D1746, 3, 0x403B45E353F7CED9),
  (0xC03B45D1745D1746, 3, 0xC03B45E353F7CED9),
  (0x3F9BED61BED61BD8, 3, 0x3F9BA5E353F7CED9),
  (0x3E7AD7F29ABCAF48, 6, 0x0000000000000000),
  (0x3FEFFFFEF39085F5, 6, 0x3FF0000000000000),
  (0x4064D55555555556, 3, 0x4064D55810624DD3),
  (0x3FE5555555555555, 2, 0x3FE570A3D70A3D71),
  (0xBF1A36E2EB1C432D, 3, 0x0000000000000000),
  (0xBE7AD7F29ABCAF48, 6, 0x0000000000000000),
  (0x8000000000000000, 3, 0x8000000000000000),
  (0xBFC0000000000000, 3, 0xBFC0000000000000),
  (0x3EA0C6F7A0B5ED8D, 6, 0x0000000000000000),
  (0x4324438E98E94EA1, 6, 0x4324438E98E94EA1)
]

end Decfmt
